UrbanInstitute/dataviz-components

src/lib/ProjectCredits/ProjectCredits.stories.svelte, src/lib/ProjectCredits/ProjectCredits.svelte, src/lib/TextBlock/TextBlock.stories.svelte, src/lib/TextBlock/TextBlock.svelte
This is mainly a change to `TextBlock`, which is then used by `ProjectCredits`. The value is now passed via child slots, namely inside a `<svelte:fragment>`.
TODO: add documentation for slots in the `TextBlock` and `ProjectCredits` stories
TODO: color reverse in `TextBlock` is now broken
=> Convert TextBlock/ProjectCredits to accept value as slot

package.json, src/lib/stores/index.js, src/lib/stores/reducedMotion.js, src/stories/reducedMotion.mdx
Adds a Svelte store for detecting prefers-reduced-motion, based on [Geoff Rich's work](https://geoffrich.net/posts/accessible-svelte-transitions/).
=> prefers-reduced-motion svelte store

src/lib/BasicDropdown/BasicDropdown.stories.svelte, src/lib/Block/Block.stories.svelte, src/lib/HeadingAlt/HeadingAlt.stories.svelte, src/lib/LogoTPCBadge/LogoTPCBadge.stories.svelte, src/lib/LogoUrban/LogoUrban.stories.svelte, src/lib/LogoUrbanBadge/LogoUrbanBadge.stories.svelte, src/lib/Navbar/Navbar.stories.svelte, src/lib/ProjectCredits/ProjectCredits.stories.svelte, src/lib/ReturnTop/ReturnTop.stories.svelte, src/lib/Scorecard/Scorecard.stories.svelte, src/lib/SocialShare/SocialShare.stories.svelte, src/lib/TextBlock/TextBlock.stories.svelte
Goal is to add text on each story page, describing the component and giving additional context.
Documentation on this parameters.docs API can be found here: https://storybook.js.org/docs/api/doc-block-description#writing-descriptions
=> Add component descriptions to story pages via parameters.docs.description.component

.github/workflows/publish.yml, .github/workflows/storybook-deploy.yml, .github/workflows/storybook-tests.yml, CHANGELOG.md
A simple update to a few under the hood action items that were due to be updated per this: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update github action workflows

CHANGELOG.md, src/lib/ChartBlock/ChartBlock.stories.svelte, src/lib/ChartBlock/ChartBlock.svelte
Add a ChartBlock component that wraps any custom visualization with optional text for:
- title
- description
- source
- notes
=> Add ChartBlock component

CHANGELOG.md, src/lib/DatawrapperIframe/DatawrapperIframe.svelte
Iterates through Datawrapper interaction events and turns them off when component is destroyed. This is useful when switching between multiple iframes and ensuring there is no duplication of events.
=> Turn off Datawrapper interaction events on destroy of component

CHANGELOG.md, src/lib/BasicDropdown/BasicDropdown.svelte
Add text overflow ellipsis and right padding to BasicDropdown
=> Add text overflow ellipsis and right padding to BasicDropdown

CHANGELOG.md, src/lib/Block/Block.stories.svelte
Just moving around and updating a bit of documentation. The layout Block component is now organized in the main "Components" folder instead of being in its own section.
=> Re-org Block component docs into component section

CHANGELOG.md, src/lib/Navbar/Navbar.stories.svelte, src/lib/Navbar/Navbar.svelte
Resolves #70 
Previously, an error was thrown if no `projectUrl` was declared in the component, even though that case was used in the story documentation. I added a default empty string for the `projectUrl` parameter and added a case for if there's a `title` given without that link, along with the story documentation for the same. This fix gives developers more options for how they want to render the component, freestyle.
I also updated the projectUrl for the TPC scenario in the docs to be a link to TPC's website, for kicks.
=> added case for no projectUrl

CHANGELOG.md, src/lib/BasicDropdown/BasicDropdown.svelte
In order to bind a variable (initially set to null) to a dropdown where there is a palceholder (null value) then the prop needs to accept a null value and not just string.
=> Make BasicDropdown value optionally null 

src/lib/utils/tpcColors.js, src/lib/utils/urbanColors.js
The way that the color utilities exported the base color constants wasn't playing well with type generation. This PR reorgs the exports so that they are recognized by the language server. Fixes #73.
=> Fix: color utils exports

CHANGELOG.md, src/lib/maps/SVGMap/ZoomControls.svelte
Fixes bug on mobile Safari where SVG icons did not display properly on ZoomControls
=> Fix: remove padding from map zoom control buttons

CHANGELOG.md, src/lib/Theme/Theme.docs.mdx
Add instructions to `Theme.docs.mdx` on how to reference css variables in intellisense. Original PR: #100
=> Patch: add theme's css variable intellisense instructions to docs

CHANGELOG.md, README.md, bin/createComponent/createComponent.js, bin/createComponent/createDocs.js, bin/createComponent/createStory.js, package-lock.json, package.json, src/docs/Intro.docs.mdx
Running `npm run create-component` will ask for a component name and create 3 boilerplate files (svelte, story, and docs). Checks for PascalCase and uses the `inquirer` package for JS-based CLI functionality (dev-only dependency).
Future features to consider:
- Ask if the folder should be in a subdir of `src/lib/`
- Ask to use a `.docs.mdx` template (instead of `.docs.md`)
=> CLI command for initializing component boilerplate

.storybook/manager.head.html, .storybook/preview-body.html, package.json, src/lib/Icons/IconClose.stories.svelte, src/lib/Icons/IconMinus.stories.svelte, src/lib/Icons/IconPlus.stories.svelte, src/lib/Icons/IconSearch.stories.svelte, src/lib/Icons/Icons.docs.mdx
Let me know what you think about some of these proposed changes, idea is to build on what you have but simplify the story setup a little bit since we'll have 30+ to create! I was also able to modify the css of the icon gallery so the items are big enough to capture the default size of our icons at 40w/h!
Note: the `package.json` edit for the icons subfolder when importing!
=> Icon gallery reorganization

CHANGELOG.md, src/lib/maps/ColorLegend/ColorLegend.svelte
Fixes a bug where ColorLegend displayed threshold scale tick marks incorrectly.
Adds option for an N/A item in legend.
=> Fix threshold scale ticks and add NA option to ColorScale

CHANGELOG.md, package-lock.json, package.json
Fixes icon export path and sets up new release
=> Fix icon exports

CHANGELOG.md, src/lib/ChartBlock/ChartBlock.svelte, src/lib/Headline/Headline.svelte
This PR adds more CSS specificity to several component-level <p> tag styles to avoid conflicts with the <Theme /> defaults.
=> Fix: <p> font sizes

.github/workflows/storybook-tests.yml, CHANGELOG.md, src/lib/maps/ColorLegend/ColorLegend.svelte, src/lib/maps/SVGPolygonLayer/SVGPolygonLayer.svelte
- Fix: Color scale resets ticks when switching from threshold scale to continuous scale
- Patch: SVGPolygonLayer uses mousedown instead of click event
=> Patch map improvements

CHANGELOG.md, src/lib/Tooltip/Tooltip.svelte
Tooltip would throw error when inside of web component. This fix checks if ancestors are instances of Element before calling getComputedStyle on them. This avoids the error.
=> Fix tooltip style calculation

CHANGELOG.md, src/lib/Tooltip/Tooltip.svelte
Tooltip now positions correctly when it is inside the shadowroot of a custom element and that custom element is inside a fixed, absolute or relatively positioned ancestor.
=> Fix: tooltip position inside shadow root

CHANGELOG.md, src/lib/Theme/Theme.svelte
The CSS variable --color-green was a kind of yellow. Updated to match style guide.
=> Patch css color green

CHANGELOG.md, src/lib/Headline/Headline.svelte
In non-apps project Stories or Data tools (by the Urban dot org categorization), Headline eyebrows link out to either [https://www.urban.org/data-tools](https://www.urban.org/data-tools) or [https://www.urban.org/stories](https://www.urban.org/stories). 
Our headline component now detects when the eyebrow is Data tool or Story (checking against lowercased version of the string) and adds the proper link out, following the style in Drupal (underline the link on hover). If the eyebrow is not Data tool or Story, it stays a p tag.
=> Patch headline eyebrow link

CHANGELOG.md, src/docs/stories/DatawrapperSwitching.stories.svelte
Patch: DatawrapperSwitching story to wrap the bottom block in `if` instead of `key`.
=> Patch for datawrapperswitching

CHANGELOG.md, src/lib/Icons/index.js
IconRefresh was in our storybook but was not exported and thus was unusable
adds IconRefresh to Icons directory export file
=> add export for IconRefresh

CHANGELOG.md, src/lib/Analytics/Analytics.svelte
To ensure page views are a decision contemplated in all cases, I added an inspect log in the analytics component which will only appear on dev. It will remind developers to consider whether to turn off page views for quickturn embed projects while not imposing heavily on longterm feature work.
=> Patch analytics inspect pageview

CHANGELOG.md, src/lib/Meta/Meta.stories.svelte, src/lib/Meta/Meta.svelte
- Adds option to hide a page from search results. This is particularly useful for content designed to be embedded in another page.
=> Feat: add robotsNoIndex to meta component

CHANGELOG.md, package-lock.json, package.json, src/lib/maps/SVGMap/SVGMap.svelte
SVGMap now allows tooltip size to be configured
=> Feat map tooltip size
