UrbanInstitute/dataviz-components

- .prettierrc
- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/BasicDropdown/BasicDropdown.svelte
- src/lib/Scorecard/Scorecard.svelte
- src/lib/style/app.css
- src/lib/utils/colors.js
- src/lib/utils/index.js
- src/stories/Colors.mdx
Adds colors module and related Storybook documentation page.
> Add color ultility module

- package-lock.json
- package.json
Fixes the utils export in package.json
> Fix exports

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/lib/Block/Block.stories.svelte
- src/lib/Block/Block.svelte
- src/lib/ProjectCredits/ProjectCredits.svelte
- src/lib/TextBlock/TextBlock.svelte
- src/lib/style/app.css
- Update props for TextBlock component to play better with ArchieML
- Better spacing for Block component on mobile
- Add wide option for Block component
> Patch textblock props

- .github/workflows/storybook-tests.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/Navbar/Navbar.stories.svelte
- src/lib/Navbar/Navbar.svelte
- src/lib/ProjectCredits/ProjectCredits.svelte
- src/lib/TextBlock/TextBlock.stories.svelte
- Make github URL in ProjectCredits an optional prop
- Updates storybook to v7.6.6
- Fixes TextBlock documentation
- Adds sticky option to Navbar
> Component options

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.test.js
- src/lib/utils/dollarFormat.js
- src/lib/utils/index.js
- src/lib/utils/index.test.js
- src/lib/utils/kebabCase.js
- src/stories/helperFunctions.mdx
Added two helper functions, kebabCase() and dollarFormat(), along with tests.
> Utilities add-in

- CHANGELOG.md
- src/lib/TextBlock/TextBlock.stories.svelte
- src/lib/TextBlock/TextBlock.svelte
Add more color options to TextBlock component.
> TextBlock color

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/index.js
> Release 0.3.1

- .prettierrc
Match prettier config with internal Urban data viz team's Svelte starter kit
> update prettier config

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/Block/Block.svelte
- src/lib/style/app.css
Change wide block width to 1160px
> Patch block width

- src/lib/Navbar/Navbar.svelte
Remove unused class in Navbar.svelte
> Remove unused class in Navbar.svelte

- CHANGELOG.md
- src/lib/SectionBreak/SectionBreak.stories.svelte
- src/lib/SectionBreak/SectionBreak.svelte
Add section break component based on several recent projects
> Section break

- src/lib/BasicDropdown/BasicDropdown.stories.svelte
- src/lib/DatawrapperIframe/DatawrapperIframe.stories.svelte
- src/lib/ReturnTop/ReturnTop.stories.svelte
- src/lib/SocialShare/SocialShare.stories.svelte
Adding an action to the `<Template>` in stories to surface the actions - [reference](https://github.com/storybookjs/addon-svelte-csf/blob/main/README.md?plain=1#L63)
> Expose actions in story for addon-actions

- CHANGELOG.md
- src/lib/BasicDropdown/BasicDropdown.svelte
Audit of event dispatching per [this docs article](https://svelte.dev/docs/component-directives#on-eventname)
> remove unnecessary programmatic event dispatch from dropdown (use declarative)

- src/lib/Button/Button.stories.svelte
- src/lib/Button/Button.svelte
- Simplifies the `<Button />` component in terms of color variants and how to pass that to a child icon.
- Adds disabled states based on new design guidance.
> Button improvements

- CHANGELOG.md
- src/lib/index.js
Exports ChartBlock from index.js
> Hotfix chartblock export

- .github/pull_request_template.md
- package-lock.json
- package.json
> Release 0.5.1

- CHANGELOG.md
- src/lib/BasicDropdown/BasicDropdown.stories.svelte
- src/lib/BasicDropdown/BasicDropdown.svelte
Don't show placeholder dropdown option if placeholder is null. Also make variables camelCase.
> Patch BasicDropdown with conditional placeholder

- CHANGELOG.md
- src/lib/Toggle/Toggle.stories.svelte
- src/lib/Toggle/Toggle.svelte
- src/lib/index.js
Initial toggle component for data visualization projects. As we continue discussions with the design team, we can update accordingly.
Features:
- label position (left or right)
- active (boolean)
- disabled (boolean)
> Toggle component

- .storybook/preview.js
- CHANGELOG.md
Ensures stories are rendered alphabetically
> Patch: Update story ordering config

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.7.1

- .storybook/preview.js
- .storybook/svelte-highlighting.js
- CHANGELOG.md
Svelte syntax highlighting in code blocks (HUGE thanks to the Axios viz team)
> Svelte syntax highlighting

- CHANGELOG.md
- src/lib/Analytics/Analytics.docs.mdx
- src/lib/Meta/Meta.docs.mdx
- src/lib/Scrolly/Scrolly.docs.mdx
- src/lib/Theme/Theme.docs.mdx
Apparently I have a habit of mis-naming this package in documentation as `@urban-institute/dataviz-components` instead of `@urbaninstitute/dataviz-components`. This PR addresses those issues.
> Fix package names in docs

- CHANGELOG.md
- src/docs/DynamicInfoStores.docs.mdx
- src/docs/Intro.docs.mdx
- src/lib/Button/Button.stories.svelte
- src/lib/Meta/Meta.svelte
- src/lib/ProjectCredits/ProjectCredits.stories.svelte
- src/lib/SocialShare/SocialShare.svelte
I noticed the Intro.docs.mdx code chunk needed to be updated but then went down the path of updating as many snake case variables as I could to camel case. Does not include color palette.
> Patch Intro code chunk and apply camel case

- CHANGELOG.md
- package-lock.json
- package.json
> Release 0.7.2

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/Pym/PymChild.docs.mdx
- src/lib/Pym/PymChild.stories.svelte
- src/lib/Pym/PymChild.svelte
- src/lib/Pym/pymChildStore.docs.mdx
- src/lib/Pym/stores.js
- src/lib/index.js
- src/lib/stores/index.js
Adds a PymChild component for use in embedded projects. Includes a way to access Pym child instance via store.
> Feat: Add PymChild component

- CHANGELOG.md
- README.md
- src/docs/Intro.docs.mdx
Contribution guidance for repo
> add contribution guidance to Intro docs and README

- CHANGELOG.md
- src/lib/LogoUrbanAnimated/LogoUrbanAnimated.stories.svelte
- src/lib/LogoUrbanAnimated/LogoUrbanAnimated.svelte
- src/lib/index.js
Adds an animated SVG Urban badge logo component.
> Feature add animated logo badge component

- src/lib/LogoUrbanAnimated/LogoUrbanAnimated.svelte
> Remove extra CSS from LogoUrbanAnimated.svelte

- CHANGELOG.md
- src/lib/Toggle/Toggle.stories.svelte
- src/lib/Toggle/Toggle.svelte
Have Toggle.svelte adhere to design team spec, the [switch pattern from W3C](https://www.w3.org/WAI/ARIA/apg/patterns/switch/), and prefers-reduced-motion CSS.
> Toggle component adheres to design, ARIA, and prefers-reduced-motion

- CHANGELOG.md
- src/lib/Toggle/Toggle.svelte
Dispatch click so on:click is available in the parent
> Add dispatched click to toggle

- CHANGELOG.md
- src/lib/ProjectCredits/ProjectCredits.svelte
Removes extra padding from list in ProjectCredits
> Fix: remove errant padding from ProjectCredits

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.10.0

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.10.1

- .github/workflows/storybook-tests.yml
- CHANGELOG.md
Simple patch to add Vitest to the list of things that run in our CI workflows.
> Patch run tests

- CHANGELOG.md
- bin/compileTheme.js
- package.json
- src/lib/Theme/Theme.docs.mdx
Compiles and exports a copy of the theme CSS as a standalone file. Addresses #86.
> Feature compile theme css

- .storybook/preview.js
- CHANGELOG.md
Update the Storybook viewport sizes to match the Urban design system breakpoints for easier visual QC.
> Patch: Update Storybook viewports

- CHANGELOG.md
- src/lib/SocialShare/SocialShare.svelte
Update the spacing between icons in the SocialShare component to match Urban.org design.
> Patch: Update SocialShare component spacing

- CHANGELOG.md
- src/lib/Toggle/Toggle.svelte
Update Toggle size to adhere to design team guidance
> Update toggle size

- CHANGELOG.md
- src/lib/BasicDropdown/BasicDropdown.svelte
Add aria-hidden="true" to icon so screenreaders don't pick it up
> Patch BasicDropdown icon accessibility

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.11.0

- CHANGELOG.md
- src/docs/stories/DatawrapperSwitching.stories.svelte
Add metadata to `dropdownData` in the Datawrapper Switching example so there are values for required props title and ariaLabel in the `<DatawrapperIframe>` component.
> Update Datawrapper Switching Example

- CHANGELOG.md
- package-lock.json
- package.json
Allows Svelte 5 apps to use this library
> Svelte 5 support

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.12.0

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.12.1

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.12.2

- CHANGELOG.md
- package-lock.json
- package.json
> Release v.0.12.3

- CHANGELOG.md
- package-lock.json
- package.json
> Release 0.12.4

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.12.5

- CHANGELOG.md
- package-lock.json
- package.json
> Release 0.13.0

- .storybook/preview-head.html
- CHANGELOG.md
- src/lib/ChartBlock/ChartBlock.svelte
- src/lib/Fonts/FontsUrban.svelte
- src/lib/Theme/Theme.svelte
Adds new typography styles, including new FuturaPT font, and associate styles.
> Feat: new typography styles

- CHANGELOG.md
- package-lock.json
- package.json
> Prep Release v0.14.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/maps/SVGPointLayer/SVGPointLayer.svelte
- src/lib/maps/SVGPolygonLayer/SVGPolygonLayer.svelte
Fixes pointer-events style name in SVGMap layers
> Fix map pointer events

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/LogoUrbanWide/LogoUrbanWide.stories.svelte
- src/lib/LogoUrbanWide/LogoUrbanWide.svelte
Tell us what this PR does or link to any related issues that describe the goal here.
> Fix urban logo wide height fix
